# Generated by Django 5.1.7 on 2025-03-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/p.png', null=True, upload_to='profile_pics/'),
        ),
    ]
