# Generated by Django 5.1.7 on 2025-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_bio',
            field=models.TextField(blank=True, help_text='سيرة ذاتية تفصيلية أو نبذة تعريفية'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(blank=True, help_text='وصف مختصر (مثال: AI Expert, UI Guru)', max_length=15),
        ),
    ]
