# Generated by Django 5.1.7 on 2025-07-20 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_full_bio_customuser_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Detailed biography or personal summary.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Phone number must start with 05 and contain exactly 10 digits.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 05 and be exactly 10 digits.', regex='^05\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Short description (e.g., AI Expert, UI Guru).', max_length=15),
        ),
    ]
