# Generated by Django 5.1.7 on 2025-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participation_policy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_color',
            field=models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', max_length=10),
        ),
    ]
