# Generated by Django 5.1.7 on 2025-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_expertrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
