# Generated by Django 5.1.7 on 2025-03-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
