# Generated by Django 5.1.7 on 2025-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('urgent', 'Urgent'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
